import "~/styles/globals.css";

import { type Metadata } from "next";
import Provider from "./StoreProvider";
import { Geist } from "next/font/google";
import { TopNav } from "~/app/_components/top-nav";

export const metadata: Metadata = {
  title: "Coincap App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  robots: {
    index: true,
    follow: true,
  },
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TopNav />
        <main>
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
